CREATE TABLE AUX_COTACOES (
    COD_PRODUTO INT NULL,
    DC_PRODUTO varchar(255) NOT NULL,
    DC_PRECO varchar(255) NOT NULL,
    DC_UNIDADE varchar(255) NOT NULL,
    DT_DATA datetime NOT NULL,
    CONSTRAINT PK_AUX_COTACOES primary key(DC_PRODUTO, DT_DATA)
);

CREATE TABLE COTACOES (
    COD_PRODUTO INT NULL,
    DC_PRODUTO varchar(255) NOT NULL,
    DC_PRECO varchar(255) NOT NULL,
    DC_UNIDADE varchar(255) NOT NULL,
    DT_DATA datetime NOT NULL,
    CONSTRAINT PK_COTACOES primary key(DC_PRODUTO, DT_DATA)
);

CREATE TABLE PRODUTOS (
    COD_PRODUTO INT NOT NULL,
    NM_PRODUTO varchar(255) NOT NULL,
    CONSTRAINT PK_PRODUTOS primary key(COD_PRODUTO, NM_PRODUTO)
);

