DELIMITER $$
 
CREATE TRIGGER UPDATE_COD_PRODUTO AFTER INSERT
ON aux_cotacoes
FOR EACH ROW
BEGIN
	IF(NEW.DC_PRODUTO = 'Açúcar - AL') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (1,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Açúcar - PB') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (2,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Açúcar - PE') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (3,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Açúcar - Santos') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (4,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Açúcar - SP') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (5,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Algodão') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (6,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Arroz') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (7,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Bezerro - MS') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (8,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Bezerro - SP') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (9,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Boi Gordo') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (10,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Café Arábica') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (11,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Café Robusta') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (12,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Citros') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (13,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Etanol Anidro -  PE') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (14,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Etanol Anidro - AL') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (15,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Etanol Anidro - MT') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (16,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Etanol Anidro - SP ') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (17,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Etanol Hidratado - AL') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (18,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Etanol Hidratado - GO') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (19,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Etanol Hidratado - MT') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (20,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Etanol Hidratado - PE') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (21,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Etanol Hidratado - SP ') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (22,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Frango Congelado ') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (23,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Frango Resfriado') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (24,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Leite') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (25,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Mandioca') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (26,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Milho') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (27,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Ovino - CE') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (28,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Ovino - MS') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (29,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Ovino - MT') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (30,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Ovino - PR') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (31,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Ovino - RS') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (32,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Ovino - SP') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (33,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Ovos') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (34,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Soja - PR') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (35,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Soja Paranaguá') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (36,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Suíno - MG') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (37,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Suíno - PR') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (38,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Suíno - RS') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (39,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Suíno - SC') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (40,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Suíno - SP') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (41,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Suíno - carcaça especial') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (42,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Trigo - PR') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (43,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
    IF(NEW.DC_PRODUTO = 'Trigo - RS') THEN INSERT IGNORE INTO cotacoes (`COD_PRODUTO`,`DC_PRODUTO`,`DC_PRECO`,`DC_UNIDADE`,`DT_DATA`) VALUES (44,NEW.`DC_PRODUTO`,NEW.`DC_PRECO`,NEW.`DC_UNIDADE`,NEW.`DT_DATA`); END IF;
END$$
 
DELIMITER ;






